[package]
name = "helix-log"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
fern = "0.7"
log = "0.4"
tokio = { version = "1", features = ["sync"] }
