name: Update

on:
  workflow_dispatch: {}

jobs:
  build:
    name: Bump grammars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Bump tree sitter grammars
        uses: matoous/helix-bump-grammars@v0.2
        with:
          token: '${{ secrets.GH_ACTIONS_PAT }}'
          pr-limit: 5
